# Generated by Django 3.0.4 on 2020-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAuthorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('authorisation_status', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Історія авторизацій користувач: ',
                'verbose_name_plural': 'Історія авторизацій користувачів:',
            },
        ),
    ]
