# Generated by Django 3.0.4 on 2020-05-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0003_repairclient_repairdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairdevice',
            name='performed_works',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='repairclient',
            name='client_work_place',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
