# Generated by Django 3.0.4 on 2020-05-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0004_auto_20200504_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairdevice',
            old_name='malfunction',
            new_name='client_malfunction',
        ),
        migrations.RenameField(
            model_name='repairdevice',
            old_name='malfunction_reason',
            new_name='complete_set_device',
        ),
        migrations.RemoveField(
            model_name='repairdevice',
            name='device_year',
        ),
    ]
