# Generated by Django 3.0.4 on 2020-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0005_auto_20200524_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repairdevice',
            old_name='performed_works',
            new_name='mulfunction',
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='all_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='price_repair',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='recommendations_repair',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='recommendations_repair_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
