# Generated by Django 3.0.4 on 2020-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0006_auto_20200524_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Спосіб доставки',
                'verbose_name_plural': 'Спосіб доставки',
            },
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='materials',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='need_spare_part',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='performed_work',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
