# Generated by Django 3.0.4 on 2020-05-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0007_auto_20200524_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='repairdevice',
            name='invoice',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='method_delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device_info.DeliveryMethod'),
        ),
    ]
