# Generated by Django 3.0.4 on 2020-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0009_repairclient_client_edrpou'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_periods', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Терміни гарантії',
                'verbose_name_plural': 'Термін гарантії',
            },
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='agreed_work_repair',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='repairdevice',
            name='agreed_work_repair_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
