# Generated by Django 3.0.4 on 2020-06-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0011_repairdevice_warranty_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRepairStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_repair_status', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Стан оплати',
                'verbose_name_plural': 'Статуси оплати',
            },
        ),
    ]
