# Generated by Django 3.0.4 on 2020-03-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200322_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Замовлений товар', 'verbose_name_plural': 'Товари в замовленні'},
        ),
    ]
