# Generated by Django 3.0.4 on 2020-04-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productinbusket_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custumer_fathername',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='custumer_surname',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
