# Generated by Django 3.0.4 on 2020-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_statusgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категорія товару: ',
                'verbose_name_plural': 'Категорії товарів',
            },
        ),
    ]
