# Generated by Django 3.0.4 on 2020-03-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categorygoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.CategoryGoods'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='status_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.StatusGoods'),
        ),
    ]
