# Generated by Django 3.0.4 on 2020-03-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200322_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_characteristic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
