# Generated by Django 3.0.4 on 2020-03-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
