# Generated by Django 3.0.4 on 2020-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200828_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCategoryGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_category', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sections_category_image', models.ImageField(default=0, upload_to='stylesheet/media/section_category_products_image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Розділ категорії товару ',
                'verbose_name_plural': 'Розділ категорій товарів',
            },
        ),
    ]
