# Generated by Django 3.0.4 on 2020-09-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sectioncategorygoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygoods',
            name='section_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.SectionCategoryGoods'),
        ),
    ]
